version: "3.7"

services:
  bedroom-server:
    container_name: bedroom-server-Bruxelles
    build: .
    dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:3000"
      - "443:3000"
    env_file:
      - .env.devBX
