version: "3.7"

services:
  bedroom-server:
    container_name: bedroom-server
    image: patrick450/bedroom
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.dev
    networks:
      - bedroom-network
    depends_on:
      - database

  database:
    container_name: postgres-container
    image: postgres
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - bedroom-network

networks:
  bedroom-network:
    driver: bridge
